create database kgcas;
use kgcas;
create table student(name varchar(32),dept varchar(5),sec char(1), marks int);
select * from student;
insert into student values("priya","ct","B",78),("priya","ct","B",54),("sam","ct","A",80),("Harshini","ct","A",35),("Maya","ct","B",25);
select * from student;
update student set name="ypd" where name="priya";
select *from student;
select * from student where marks<60;
select name,dept,sec from student;
alter table student add Gender char(1);
select *from student;
update  student set Gender="F" ;
select *from student;
insert into student values("arun","IT","B",89,"M");
alter table student drop column dept ;
select *from student;
truncate table student;
drop database kgcas;
